### ISSUE TITLE
Mention "App Manager" role on App Store Connect API docs

### ISSUE THREAD

**Issue by chrmcg** [fastlane/docs#1050]
http://docs.fastlane.tools/app-store-connect-api/

After reading this page, I created an API key in https://appstoreconnect.apple.com/access/api as instructed, and of the five available access levels (Admin, App Manager, Developer, Finance, Sales and Reports) I chose "Developer".

But it turns out that in the `upload_to_testflight` action, setting `changelog` with a "Developer" API key active results in the following error:
`Could not set changelog: This request is forbidden for security reasons - The API key in use does not allow this request`

and setting `beta_app_feedback_email` or `beta_app_description` results in:
`Could not set beta_app_feedback_email and/or beta_app_description: This request is forbidden for security reasons - The API key in use does not allow this request`

After trying again with an "App Manager" API key, no such problems.

Could we update the docs to mention that "App Manager"-level permissions are needed for some fields, including these three?

**Comment by rogerluan** [comment]
Not sure if this should be documented by us. The roles and their permissions are clear from App Store Connect's website, and this permission issue is not strict to the API key, it shares all the permissions and limitations with the User's Roles. I think users (from fastlane or users that don't use fastlane) should follow the documentation provided by Apple for this, otherwise we'd be always playing cat and mouse with Apple's official documentation: we duplicate all their roles & permissions, then they release a new feature/permission and our docs become outdated immediately, then we have to update it again, and the cycle repeats. 

This is one the links where you can see the permissions for each role: https://developer.apple.com/support/roles/
