### ISSUE TITLE
License of the docs repo design

### ISSUE THREAD

**Issue by buger** [fastlane/docs#254]
Hello! 

You have such a nice custom CSS for the documentation site, and I'm wondering if you allow to re-use it.

I did not found any notes about the license of this repository, so before stealing your code I decided to ask first 😇

**Comment by KrauseFx** [comment]
Nice catch, thanks for bringing this to our attention @buger. I just looked, and we actually took the design from https://docs.fabric.io/, so I don't think we can license the whole repo as MIT, however I can look into licensing the actual page's content under MIT, since it's just taken from the fastlane/fastlane main repo.

**Comment by joshdholtz** [comment]
@KrauseFx Any update/thoughts on how to license this repo?
