### ISSUE TITLE
More explaination for using Fastlane Flutter and Travis Ci combined.

### ISSUE THREAD

**Issue by HerrNiklasRaab** [fastlane/docs#739]
The point 3 of chapter "Cloud build and deploy setup" of this  side: https://flutter.io/docs/deployment/fastlane-cd
Should be explained much more detailed here: https://docs.fastlane.tools/getting-started/cross-platform/flutter/

I have totally no idea how to setup flutter fastlane and travis combined.

**Comment by janpio** [comment]
Oh hey, we met on Stack Overflow a few minutes ago regarding the same problem ;)

I somehow agree that 3) of that headline is not the best, but we can't do much about it here. Better create an issue over at the flutter website repo: https://github.com/flutter/website/issues/new?title=%27Continuous%20Delivery%20using%20fastlane%20with%20Flutter%27%20page%20issue&body=Page%20URL:%20https://flutter.io/docs/deployment/fastlane-cd.html%0D%0APage%20source:%20https://github.com/flutter/website/tree/master/src/docs/deployment/fastlane-cd.md%0D%0A%0D%0A%3C!--%20ADD%20YOUR%20DESCRIPTION%20OF%20THE%20PAGE%20ISSUE%20HERE:%20--%3E Then we cna maybe create a PR for that file and improve it: https://github.com/flutter/website/blob/master/src/docs/deployment/fastlane-cd.md

(Feel free to link to that issue here or mention me directly, then I can take a look as myself. Sounds like a nice weekend project to learn about flutter)

**Comment by HerrNiklasRaab** [comment]
Done
